spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    url: jdbc:mysql://localhost:3306/${database}?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    password: ${password}
  jpa:
    show-sql: true
logging:
  config: classpath:log4j2.xml
server:
  port: ${port}
